Auth using express, prisma, jwt, sqlite
smakosh/roll-your-own-auth pull request #2
Opened 2024-03-28 16:11 UTC by Piipas

- Express
- Prisma
- JWT
- SQLite

2024-03-29 16:38 UTC, smakosh requested changes
Thanks for the PR, overall looks good, once the points raised are fixed, I will merge it!

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/README.md
Can you update this README?

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/package.json
> +    "name": "rest-express-prisma-sessions-sqlite",
Change name here to match folder name of this boilerplate

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/package.json
> +    },
Add your details here

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/src/features/auth/controllers/loginHandler.ts
> +        httpOnly: true,
Add `sameSite: "Lax"`

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/src/features/auth/controllers/refreshHandler.ts
> +        httpOnly: true,
Add `sameSite: "Lax"`

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/src/features/auth/controllers/signupHandler.ts
> +        httpOnly: true,
Add `sameSite: "Lax"`

2024-03-29 16:38 UTC, smakosh commented on examples/rest-express-prisma-jwt-sqlite/src/features/auth/middlewares/passport.ts
> +    console.log(req.cookies[cookieName]);
To be removed

2024-03-31 10:43 UTC, smakosh approved these changes
LGTM!

2024-03-31 10:43 UTC, merged

2024-03-31 10:44 UTC, smakosh commented
@all-contributors please add @Piipas for code

2024-04-27 06:17 UTC, endlesss-builds commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
JanShi, @acheo, @lylepratt, @Horassi, @kemen209, @rroemhild, @iagobelo, @marcus-campos, @iam4x, @endziu, @matek2305, @weisk, @haydenfreewillsmiley, @mlsieg, @motocarota, @damdeez, @mfiumara, @paritygeeker, @sangron, @ankion, @iwangshuo, @kishanjasani, @adampolehonky, @Babolero, @Wakizashimaster, @NiouMishuai, @Maboulmagd, @iammert, @leslyarun, @hustshawn, @fpauser, @mecitsem, @TomiToivio, @DavidValin, @AndrzejxW, @samadsajanlal, @GoodBoy962, @ngo275, @rick-ridgley, @ujjwalagrawal17, @geekwho-eth, @Jumballaya, @SCWhite, @YuehChuan, @larskastelein, @jasonoconner2017, @amoskyler, @benkuly, @EigenSolver, @snowlove

2024-04-28 21:50 UTC, sobin007 commented
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
formiganinja, @dantehemerson, @rmtnong, @aceboogie8519, @limkaleb, @belkizozkan, @mishkajul, @xavierca, @PeiXiaoMeng, @EM28715, @tdkr, @LoYeeee, @nesterone, @joshrieken, @damoncro, @ast850328, @windfall007, @lucadenhez, @garethnic, @Metoui24, @Punkte, @serendipity89, @fxghqc, @lyciumlee, @XHalso, @santihugin, @Dossi1, @casperhale, @yunbow, @thomascarvalho, @Lykhoyda, @randycml, @toomastahves, @derekr, @trojanshare, @shohan4556, @tommyliu9, @OC0311, @banerRana, @zeque98, @mike182uk, @zjffun, @MarkTangCd, @NorthHub, @laike, @AhmedAbdulrahman, @somestepan, @dennis-gonzales, @fqinhong, @liyuchenf1